name: microformats
description: A library for parsing and constructing HTML and JSON microformats.
version: 0.0.1
repository: https://github.com/afstanton/microformats

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
